# Presten

I en kirke sitter presten og klokkeren og snakker med tre kvinner (Du får vite at kvinnene alle har en alder mellom 1 og 100 år). Etter en tid takker kvinnene for seg, og presten og klokkeren blir sittende. "Vet du hvor gamle de kvinnene var?" spør presten. "Nei, det gjør jeg ikke," sier klokkeren. "Jeg kan si deg så mye som at produktet av aldrene deres var 2450, og at summen av aldrene deres var det dobbelte av alderen din," sier presten. 

Klokkeren grubler over dette til neste dag, og blir da spurt av presten om han har funnet ut av det ennå. Klokkeren må svare nei på dette. "Da kan jeg kanskje også fortelle deg at av oss fem var jeg den eldste," sier presten. "Å ja," sier klokkeren, "da er det jo lett!". 

Hvor gammel er presten?

### Løsning

Starter med å finne alle faktorene som gir produktet 2450

In [1]:
import numpy as np

abc = []
for a in range(1,100):
    for b in range(1, 100):
        for c in range(1, 100):
            if a*b*c == 2450:
                t = [a,b,c]
                abc.append(t) 
                
abc = np.array(abc)             

Sorterer så arrayet for lettere å fjerne alle kombinasjoner som ikke er unike

In [2]:
abc.sort()
abc_redusert = np.unique(abc, axis=0)
abc_redusert

array([[ 1, 25, 98],
       [ 1, 35, 70],
       [ 1, 49, 50],
       [ 2, 25, 49],
       [ 2, 35, 35],
       [ 5,  5, 98],
       [ 5,  7, 70],
       [ 5, 10, 49],
       [ 5, 14, 35],
       [ 7,  7, 50],
       [ 7, 10, 35],
       [ 7, 14, 25]])

Vi finner så summen av de resterende alderene til kvinnene. 

In [3]:
abc_sum = np.sum(abc_redusert, axis=1)
abc_sum

array([124, 106, 100,  76,  72, 108,  82,  64,  54,  64,  52,  46])

In [4]:
u, c = np.unique(abc_sum, return_counts=True)
dup = u[c > 1]
dup

array([64])

Vi kan nå anta at den eneste kombinasjonen av aldere som gjør at kokken blir usikker må være 64. Kokke må da være 32

For å finne prestens alter må vi se på alderene som gir summen 64

In [5]:
for alternativ in abc_redusert:
    if sum(alternativ) == dup[0]:
        print(alternativ)
        

[ 5 10 49]
[ 7  7 50]


Den eneste alder til presten som hjelper er hvis en av alternativene blur luket bort. Presten må derfor være **50 år**.